language: python
python:
  - "2.7"
sudo: false
addons:
  apt:
    packages:
      # not yet whitelisted by travis, reverted to pip
      #- python-joblib
      #- python-networkx
      - python-matplotlib
matrix:
  include:
    - python: 2.7
      env: NUMPY=1.8 SCIPY=0.14 SCIKIT=0.16
before_install:
  - travis_retry wget http://repo.continuum.io/miniconda/Miniconda-3.8.3-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
install:
  # python virtualenv not to be used with anaconda
  #- virtualenv .venv
  #- . .venv/bin/activate
  # install numy using anaconda
  - conda create --yes -n .venv python=$TRAVIS_PYTHON_VERSION
  - source activate .venv
  - conda install --yes "numpy>=1.8" "scipy>=0.14" "scikit-learn>=0.16"
  - pip install setuptools
  - pip install flake8
  - pip install nose
  # manual package installations, should eventually handled by
  # "pip install ."
  - pip install dill
  - pip install requests
  - pip install esmre
  - pip install joblib
  - pip install networkx
script:
  - flake8 . --exclude=.venv --ignore=E501
  - nosetests
