language: python
python:
  - "2.7"
  # disabled because esmre won't install with python 3.4
  # - "3.4"
sudo: false
before_install:
  # setup miniconda distribution
  - travis_retry wget http://repo.continuum.io/miniconda/Miniconda-3.8.3-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda update --yes conda
install:
  # packages from anaconda distribution
  - conda create --yes -n condaenv python=$TRAVIS_PYTHON_VERSION
  - source activate condaenv
  - conda install --yes nose
  - conda install --yes "numpy>=1.8" "scipy>=0.14" "scikit-learn>=0.16"
  - conda install --yes matplotlib
  - conda install --yes cvxopt
  - pip install git+https://github.com/nils-werner/pymf.git
  - pip install scikit-neuralnetwork
  # packages for running tests
  - pip install setuptools
  - pip install flake8
  # packages specified by setup.py
  - pip install .
script:
  - flake8 . --exclude=.venv --ignore=E501
  # run nose with doctests
  # excludes files with missing or broken dependencies
  - nosetests --with-doctest -I selector.py -I embedding.py -I obabel.py
